kind: Project
apiVersion: project.openshift.io/v1
metadata:
  labels:
    argocd.argoproj.io/managed-by: "openshift-gitops"
  name: advanced-cluster-management
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec: {}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: advanced-cluster-management-v2.10.1
  namespace: open-cluster-management
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  targetNamespaces:
  - open-cluster-management
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: advanced-cluster-management
  namespace: open-cluster-management
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  channel: release-2.10
  installPlanApproval: Automatic
  name: advanced-cluster-management
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: advanced-cluster-management.v2.10.1
---
apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  name: multiclusterhub
  namespace: open-cluster-management
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  availabilityConfig: Basic