apiVersion: v1
kind: Namespace
metadata:
  name: hello-ocp
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-ocp
  name: hello-ocp
  namespace: hello-ocp
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-ocp
  strategy: {}
  template:
    metadata:
      labels:
        app: hello-ocp
    spec:
      containers:
      - image: registry.redhat.io/openshift4/ose-hello-openshift-rhel8
        name: hello-ocp
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-ocp
  name: hello-ocp
  namespace: hello-ocp
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: bgd
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: hello-ocp
  name: hello-ocp
  namespace: hello-ocp
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: hello-ocp
    weight: 100
