apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  annotations:
    capacity.cluster-autoscaler.kubernetes.io/labels: kubernetes.io/arch=amd64
    machine.openshift.io/GPU: "0"
    machine.openshift.io/memoryMb: "16384"
    machine.openshift.io/vCPU: "4"
  creationTimestamp: "2024-04-17T18:09:58Z"
  generation: 1
  labels:
    machine.openshift.io/cluster-api-cluster: hubcluster-n76v7
  name: new-demo-machineset
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: hubcluster-n76v7
      machine.openshift.io/cluster-api-machineset: new-demo-machineset
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: hubcluster-n76v7
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: new-demo-machineset
    spec:
      lifecycleHooks: {}
      metadata: {}
      providerSpec:
        value:
          ami:
            id: ami-049d8fda91038a0fd
          apiVersion: machine.openshift.io/v1beta1
          blockDevices:
          - ebs:
              encrypted: true
              iops: 2000
              kmsKey:
                arn: ""
              volumeSize: 500
              volumeType: io1
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: hubcluster-n76v7-worker-profile
          instanceType: m5.xlarge
          kind: AWSMachineProviderConfig
          metadata:
            creationTimestamp: null
          metadataServiceOptions: {}
          placement:
            availabilityZone: us-east-2c
            region: us-east-2
          securityGroups:
          - filters:
            - name: tag:Name
              values:
              - hubcluster-n76v7-worker-sg
          subnet:
            filters:
            - name: tag:Name
              values:
              - hubcluster-n76v7-private-us-east-2c
          tags:
          - name: kubernetes.io/cluster/hubcluster-n76v7
            value: owned
          userDataSecret:
            name: worker-user-data